language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jasenpan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jasenpan/docker-react npm run test

deploy:
  provider: "elasticbeanstalk"
  region: "ap-southeast-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-462032037128"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
